services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: my_database
    volumes:
      - ./dBase/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend

  flask:
    build: ./flask
    container_name: flask_app
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/my_database
    networks:
      - backend

  front:
    build: ./front
    container_name: front_app
    volumes:
      - ./front:/usr/share/nginx/html
    networks:
      - backend

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./front:/usr/share/nginx/html
    depends_on:
      - flask
      - front
    networks:
      - backend

networks:
  backend:
    driver: bridge
